// reference/src/components/InternDashboard.tsx
import React, { useState } from 'react';
import { 
  User, 
  FileText, 
  ClipboardList, 
  Star, 
  FolderOpen,
  Home,
  Settings,
  Bell,
  LogOut,
  Calendar,
  Award,
  BookOpen
} from 'lucide-react';
import { Button } from './ui/button';
import { Badge } from './ui/badge';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from './ui/card';
import { Sidebar, SidebarContent, SidebarHeader, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarProvider, SidebarTrigger } from './ui/sidebar';
import { useAuth } from './AuthContext';
import { Progress } from './ui/progress';
import { Avatar, AvatarFallback } from './ui/avatar';

const internNavigation = [
  { id: 'dashboard', name: 'Dashboard', icon: Home },
  { id: 'profile', name: 'My Profile', icon: User },
  { id: 'applications', name: 'My Applications', icon: FileText, badge: 2 },
  { id: 'tasks', name: 'My Tasks', icon: ClipboardList, badge: 3 },
  { id: 'evaluations', name: 'Evaluations', icon: Star },
  { id: 'documents', name: 'Documents', icon: FolderOpen },
  { id: 'learning', name: 'Learning', icon: BookOpen },
];

const InternDashboardContent: React.FC = () => {
  const { user } = useAuth();

  const mockTasks = [
    { id: 1, title: 'Complete onboarding documentation', status: 'pending', priority: 'high', dueDate: '2025-01-10' },
    { id: 2, title: 'Review project requirements', status: 'in-progress', priority: 'medium', dueDate: '2025-01-12' },
    { id: 3, title: 'Submit weekly report', status: 'completed', priority: 'low', dueDate: '2025-01-08' }
  ];

  const mockApplications = [
    { id: 1, position: 'Software Engineering Intern', company: 'TechCorp', status: 'under-review', appliedDate: '2025-01-05' },
    { id: 2, position: 'Marketing Intern', company: 'StartupXYZ', status: 'interview-scheduled', appliedDate: '2025-01-03' }
  ];

  const completedTasks = mockTasks.filter(task => task.status === 'completed').length;
  const progressPercentage = (completedTasks / mockTasks.length) * 100;

  return (
    <div className="space-y-6">
      {/* Welcome Section */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-semibold">Welcome back, {user?.name}!</h1>
          <p className="text-muted-foreground">Here's your internship overview</p>
        </div>
        <div className="flex items-center gap-2">
          <Badge variant="secondary">{user?.major}</Badge>
          <Badge variant="outline">{user?.university}</Badge>
        </div>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Active Tasks</CardTitle>
            <ClipboardList className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{mockTasks.filter(t => t.status !== 'completed').length}</div>
            <p className="text-xs text-muted-foreground">
              {completedTasks} completed
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Applications</CardTitle>
            <FileText className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{mockApplications.length}</div>
            <p className="text-xs text-muted-foreground">
              1 interview scheduled
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Progress</CardTitle>
            <Award className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{Math.round(progressPercentage)}%</div>
            <Progress value={progressPercentage} className="mt-2" />
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Evaluation</CardTitle>
            <Star className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">4.2</div>
            <p className="text-xs text-muted-foreground">
              Average rating
            </p>
          </CardContent>
        </Card>
      </div>

      {/* Quick Actions & Recent Activity */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Recent Tasks */}
        <Card>
          <CardHeader>
            <CardTitle>Recent Tasks</CardTitle>
            <CardDescription>Your latest assignments and their status</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            {mockTasks.map((task) => (
              <div key={task.id} className="flex items-center justify-between p-3 border rounded-lg">
                <div className="flex-1">
                  <p className="font-medium text-sm">{task.title}</p>
                  <div className="flex items-center gap-2 mt-1">
                    <Badge 
                      variant={task.status === 'completed' ? 'default' : task.status === 'in-progress' ? 'secondary' : 'outline'}
                      className="text-xs"
                    >
                      {task.status.replace('-', ' ')}
                    </Badge>
                    <Badge 
                      variant={task.priority === 'high' ? 'destructive' : task.priority === 'medium' ? 'secondary' : 'outline'}
                      className="text-xs"
                    >
                      {task.priority}
                    </Badge>
                  </div>
                </div>
                <div className="text-xs text-muted-foreground">
                  Due: {new Date(task.dueDate).toLocaleDateString()}
                </div>
              </div>
            ))}
          </CardContent>
        </Card>

        {/* Application Status */}
        <Card>
          <CardHeader>
            <CardTitle>Application Status</CardTitle>
            <CardDescription>Track your internship applications</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            {mockApplications.map((app) => (
              <div key={app.id} className="flex items-center justify-between p-3 border rounded-lg">
                <div className="flex-1">
                  <p className="font-medium text-sm">{app.position}</p>
                  <p className="text-sm text-muted-foreground">{app.company}</p>
                  <Badge 
                    variant={app.status === 'interview-scheduled' ? 'default' : 'secondary'}
                    className="text-xs mt-1"
                  >
                    {app.status.replace('-', ' ')}
                  </Badge>
                </div>
                <div className="text-xs text-muted-foreground">
                  Applied: {new Date(app.appliedDate).toLocaleDateString()}
                </div>
              </div>
            ))}
          </CardContent>
        </Card>
      </div>

      {/* Upcoming Events */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Calendar className="h-5 w-5" />
            Upcoming Events
          </CardTitle>
          <CardDescription>Your schedule for the next few days</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-3">
            <div className="flex items-center gap-3 p-3 border rounded-lg">
              <div className="w-2 h-2 bg-blue-500 rounded-full"></div>
              <div className="flex-1">
                <p className="font-medium text-sm">Team Meeting</p>
                <p className="text-xs text-muted-foreground">Project kickoff and role assignments</p>
              </div>
              <div className="text-xs text-muted-foreground">Tomorrow, 2:00 PM</div>
            </div>
            <div className="flex items-center gap-3 p-3 border rounded-lg">
              <div className="w-2 h-2 bg-green-500 rounded-full"></div>
              <div className="flex-1">
                <p className="font-medium text-sm">Interview - StartupXYZ</p>
                <p className="text-xs text-muted-foreground">Marketing Intern position</p>
              </div>
              <div className="text-xs text-muted-foreground">Jan 12, 10:00 AM</div>
            </div>
            <div className="flex items-center gap-3 p-3 border rounded-lg">
              <div className="w-2 h-2 bg-orange-500 rounded-full"></div>
              <div className="flex-1">
                <p className="font-medium text-sm">Evaluation Meeting</p>
                <p className="text-xs text-muted-foreground">Monthly performance review</p>
              </div>
              <div className="text-xs text-muted-foreground">Jan 15, 3:00 PM</div>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

const InternProfile: React.FC = () => {
  const { user } = useAuth();

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle>My Profile</CardTitle>
          <CardDescription>Your personal and academic information</CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="flex items-center gap-4">
            <Avatar className="w-20 h-20">
              <AvatarFallback className="text-lg">
                {user?.name?.split(' ').map(n => n[0]).join('').toUpperCase()}
              </AvatarFallback>
            </Avatar>
            <div>
              <h3 className="text-xl font-semibold">{user?.name}</h3>
              <p className="text-muted-foreground">{user?.email}</p>
              <Badge variant="secondary" className="mt-1">{user?.role}</Badge>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="space-y-4">
              <h4 className="font-medium">Contact Information</h4>
              <div className="space-y-2">
                <div>
                  <label className="text-sm text-muted-foreground">Email</label>
                  <p>{user?.email}</p>
                </div>
                <div>
                  <label className="text-sm text-muted-foreground">Phone</label>
                  <p>{user?.phone || 'Not provided'}</p>
                </div>
              </div>
            </div>

            <div className="space-y-4">
              <h4 className="font-medium">Academic Information</h4>
              <div className="space-y-2">
                <div>
                  <label className="text-sm text-muted-foreground">University</label>
                  <p>{user?.university || 'Not provided'}</p>
                </div>
                <div>
                  <label className="text-sm text-muted-foreground">Major</label>
                  <p>{user?.major || 'Not provided'}</p>
                </div>
                <div>
                  <label className="text-sm text-muted-foreground">Expected Graduation</label>
                  <p>{user?.graduationDate ? new Date(user.graduationDate + '-01').toLocaleDateString('en-US', { year: 'numeric', month: 'long' }) : 'Not provided'}</p>
                </div>
              </div>
            </div>
          </div>

          {user?.skills && user.skills.length > 0 && (
            <div className="space-y-2">
              <h4 className="font-medium">Skills & Interests</h4>
              <div className="flex flex-wrap gap-2">
                {user.skills.map((skill, index) => (
                  <Badge key={index} variant="outline">{skill}</Badge>
                ))}
              </div>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
};

export const InternDashboard: React.FC = () => {
  const [activeSection, setActiveSection] = useState('dashboard');
  const { user, logout } = useAuth();

  const renderContent = () => {
    switch (activeSection) {
      case 'dashboard':
        return <InternDashboardContent />;
      case 'profile':
        return <InternProfile />;
      case 'applications':
        return <div className="text-center py-12 text-muted-foreground">Applications section coming soon...</div>;
      case 'tasks':
        return <div className="text-center py-12 text-muted-foreground">Tasks section coming soon...</div>;
      case 'evaluations':
        return <div className="text-center py-12 text-muted-foreground">Evaluations section coming soon...</div>;
      case 'documents':
        return <div className="text-center py-12 text-muted-foreground">Documents section coming soon...</div>;
      case 'learning':
        return <div className="text-center py-12 text-muted-foreground">Learning section coming soon...</div>;
      default:
        return <InternDashboardContent />;
    }
  };

  return (
    <SidebarProvider>
      <div className="flex h-screen w-full">
        <Sidebar>
          <SidebarHeader className="border-b border-sidebar-border p-4">
            <div className="flex items-center gap-2">
              <div className="w-8 h-8 bg-primary rounded-lg flex items-center justify-center">
                <User className="w-4 h-4 text-primary-foreground" />
              </div>
              <div>
                <h2 className="font-semibold">InternHub</h2>
                <p className="text-sm text-muted-foreground">Intern Portal</p>
              </div>
            </div>
          </SidebarHeader>
          
          <SidebarContent>
            <SidebarMenu className="p-2">
              {internNavigation.map((item) => (
                <SidebarMenuItem key={item.id}>
                  <SidebarMenuButton
                    isActive={activeSection === item.id}
                    onClick={() => setActiveSection(item.id)}
                    className="w-full justify-start"
                  >
                    <item.icon className="w-4 h-4" />
                    <span>{item.name}</span>
                    {item.badge && (
                      <Badge variant="secondary" className="ml-auto">
                        {item.badge}
                      </Badge>
                    )}
                  </SidebarMenuButton>
                </SidebarMenuItem>
              ))}
            </SidebarMenu>

            <div className="mt-auto p-4 border-t border-sidebar-border">
              <SidebarMenu>
                <SidebarMenuItem>
                  <SidebarMenuButton>
                    <Settings className="w-4 h-4" />
                    <span>Settings</span>
                  </SidebarMenuButton>
                </SidebarMenuItem>
                <SidebarMenuItem>
                  <SidebarMenuButton onClick={logout}>
                    <LogOut className="w-4 h-4" />
                    <span>Logout</span>
                  </SidebarMenuButton>
                </SidebarMenuItem>
              </SidebarMenu>
            </div>
          </SidebarContent>
        </Sidebar>

        <div className="flex-1 flex flex-col">
          <header className="border-b border-border bg-card p-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-4">
                <SidebarTrigger />
                <h1 className="capitalize">
                  {internNavigation.find(item => item.id === activeSection)?.name || 'Dashboard'}
                </h1>
              </div>
              
              <div className="flex items-center gap-2">
                <Button variant="ghost" size="icon">
                  <Bell className="w-4 h-4" />
                </Button>
                <Avatar>
                  <AvatarFallback>
                    {user?.name?.split(' ').map(n => n[0]).join('').toUpperCase()}
                  </AvatarFallback>
                </Avatar>
              </div>
            </div>
          </header>

          <main className="flex-1 overflow-auto p-6 bg-background">
            {renderContent()}
          </main>
        </div>
      </div>
    </SidebarProvider>
  );
};

// Frontend/reference theme/Intern Management System (1)/src/src/app/components/intern-dashboard/intern-dashboard.component.ts
import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { AuthService } from '../../services/auth.service';

type NavigationItem = {
  id: string;
  name: string;
  icon: string;
  badge?: number;
};

@Component({
  selector: 'app-intern-dashboard',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './intern-dashboard.component.html',
  styleUrl: './intern-dashboard.component.scss'
})
export class InternDashboardComponent {
  activeSection = signal('dashboard');
  sidebarCollapsed = signal(false);

  internNavigation: NavigationItem[] = [
    { id: 'dashboard', name: 'Dashboard', icon: 'home' },
    { id: 'profile', name: 'My Profile', icon: 'user' },
    { id: 'applications', name: 'My Applications', icon: 'file-text', badge: 2 },
    { id: 'tasks', name: 'My Tasks', icon: 'clipboard-list', badge: 3 },
    { id: 'evaluations', name: 'Evaluations', icon: 'star' },
    { id: 'documents', name: 'Documents', icon: 'folder' },
    { id: 'learning', name: 'Learning', icon: 'book' },
  ];

  constructor(public authService: AuthService) {}

  setActiveSection(sectionId: string): void {
    this.activeSection.set(sectionId);
  }

  toggleSidebar(): void {
    this.sidebarCollapsed.set(!this.sidebarCollapsed());
  }

  logout(): void {
    this.authService.logout();
  }

  getCurrentSectionName(): string {
    const current = this.internNavigation.find(item => item.id === this.activeSection());
    return current ? current.name : 'Dashboard';
  }

  getUserInitials(): string {
    const user = this.authService.getCurrentUser();
    if (user?.name) {
      return user.name.split(' ').map(n => n[0]).join('').toUpperCase();
    }
    return 'IN';
  }

  // Mock data methods
  getMockTasks() {
    return [
      { id: 1, title: 'Complete onboarding documentation', status: 'pending', priority: 'high', dueDate: '2025-01-10' },
      { id: 2, title: 'Review project requirements', status: 'in-progress', priority: 'medium', dueDate: '2025-01-12' },
      { id: 3, title: 'Submit weekly report', status: 'completed', priority: 'low', dueDate: '2025-01-08' }
    ];
  }

  getMockApplications() {
    return [
      { id: 1, position: 'Software Engineering Intern', company: 'TechCorp', status: 'under-review', appliedDate: '2025-01-05' },
      { id: 2, position: 'Marketing Intern', company: 'StartupXYZ', status: 'interview-scheduled', appliedDate: '2025-01-03' }
    ];
  }

  getCompletedTasksCount(): number {
    return this.getMockTasks().filter(task => task.status === 'completed').length;
  }

  getProgressPercentage(): number {
    const tasks = this.getMockTasks();
    const completedTasks = tasks.filter(task => task.status === 'completed').length;
    return Math.round((completedTasks / tasks.length) * 100);
  }

  formatDate(dateString: string): string {
    return new Date(dateString).toLocaleDateString();
  }
}
<div class="flex h-screen w-full">
  <!-- Sidebar -->
  <div class="bg-sidebar text-sidebar-foreground border-r border-sidebar-border" [class.w-64]="!sidebarCollapsed()" [class.w-16]="sidebarCollapsed()">
    <!-- Header -->
    <div class="border-b border-sidebar-border p-4">
      <div class="flex items-center gap-2">
        <div class="w-8 h-8 bg-primary rounded-lg flex items-center justify-center">
          <svg class="w-4 h-4 text-primary-foreground" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
          </svg>
        </div>
        @if (!sidebarCollapsed()) {
          <div>
            <h2 class="font-semibold">InternHub</h2>
            <p class="text-sm text-muted-foreground">Intern Portal</p>
          </div>
        }
      </div>
    </div>
    
    <!-- Navigation -->
    <div class="p-2">
      @for (item of internNavigation; track item.id) {
        <button
          (click)="setActiveSection(item.id)"
          [class]="'w-full flex items-center gap-3 px-3 py-2 rounded-md text-sm font-medium transition-colors ' + 
            (activeSection() === item.id 
              ? 'bg-sidebar-accent text-sidebar-accent-foreground' 
              : 'text-sidebar-foreground hover:bg-sidebar-accent hover:text-sidebar-accent-foreground')"
        >
          <!-- Dynamic Icons -->
          @switch (item.icon) {
            @case ('home') {
              <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
              </svg>
            }
            @case ('user') {
              <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
              </svg>
            }
            @case ('file-text') {
              <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
            }
            @case ('clipboard-list') {
              <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01" />
              </svg>
            }
            @case ('star') {
              <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z" />
              </svg>
            }
            @case ('folder') {
              <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-6l-2-2H5a2 2 0 00-2 2z" />
              </svg>
            }
            @case ('book') {
              <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.246 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
              </svg>
            }
          }
          
          @if (!sidebarCollapsed()) {
            <span>{{ item.name }}</span>
            @if (item.badge) {
              <span class="ml-auto bg-secondary text-secondary-foreground px-2 py-1 text-xs rounded-full">
                {{ item.badge }}
              </span>
            }
          }
        </button>
      }
    </div>

    <!-- Footer -->
    <div class="mt-auto p-4 border-t border-sidebar-border">
      <button
        (click)="logout()"
        [class]="'w-full flex items-center gap-3 px-3 py-2 rounded-md text-sm font-medium transition-colors text-sidebar-foreground hover:bg-sidebar-accent hover:text-sidebar-accent-foreground'"
      >
        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
        </svg>
        @if (!sidebarCollapsed()) {
          <span>Logout</span>
        }
      </button>
    </div>
  </div>

  <!-- Main Content -->
  <div class="flex-1 flex flex-col">
    <!-- Header -->
    <header class="border-b border-border bg-card p-4">
      <div class="flex items-center justify-between">
        <div class="flex items-center gap-4">
          <button
            (click)="toggleSidebar()"
            class="p-2 hover:bg-accent rounded-md"
          >
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
            </svg>
          </button>
          <h1 class="capitalize">{{ getCurrentSectionName() }}</h1>
        </div>
        
        <div class="flex items-center gap-2">
          <button class="p-2 hover:bg-accent rounded-md">
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-5 5-5-5h5zm0 0V9a6 6 0 10-12 0v8" />
            </svg>
          </button>
          <div class="w-8 h-8 bg-muted rounded-full flex items-center justify-center">
            <span class="text-sm">{{ getUserInitials() }}</span>
          </div>
        </div>
      </div>
    </header>

    <!-- Content Area -->
    <main class="flex-1 overflow-auto p-6 bg-background">
      @switch (activeSection()) {
        @case ('dashboard') {
          <div class="space-y-6">
            <!-- Welcome Section -->
            <div class="flex items-center justify-between">
              <div>
                <h1 class="text-2xl font-semibold">Welcome back, {{ authService.user()?.name }}!</h1>
                <p class="text-muted-foreground">Here's your internship overview</p>
              </div>
              <div class="flex items-center gap-2">
                <span class="px-2 py-1 text-xs rounded-full bg-secondary text-secondary-foreground">
                  {{ authService.user()?.major }}
                </span>
                <span class="px-2 py-1 text-xs rounded-full border">
                  {{ authService.user()?.university }}
                </span>
              </div>
            </div>

            <!-- Stats Cards -->
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
              <!-- Active Tasks -->
              <div class="rounded-lg border bg-card text-card-foreground shadow-sm p-6">
                <div class="flex flex-row items-center justify-between space-y-0 pb-2">
                  <h3 class="tracking-tight text-sm font-medium">Active Tasks</h3>
                  <svg class="h-4 w-4 text-muted-foreground" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01" />
                  </svg>
                </div>
                <div>
                  <div class="text-2xl font-bold">{{ getMockTasks().filter(t => t.status !== 'completed').length }}</div>
                  <p class="text-xs text-muted-foreground">
                    {{ getCompletedTasksCount() }} completed
                  </p>
                </div>
              </div>

              <!-- Applications -->
              <div class="rounded-lg border bg-card text-card-foreground shadow-sm p-6">
                <div class="flex flex-row items-center justify-between space-y-0 pb-2">
                  <h3 class="tracking-tight text-sm font-medium">Applications</h3>
                  <svg class="h-4 w-4 text-muted-foreground" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                  </svg>
                </div>
                <div>
                  <div class="text-2xl font-bold">{{ getMockApplications().length }}</div>
                  <p class="text-xs text-muted-foreground">
                    1 interview scheduled
                  </p>
                </div>
              </div>

              <!-- Progress -->
              <div class="rounded-lg border bg-card text-card-foreground shadow-sm p-6">
                <div class="flex flex-row items-center justify-between space-y-0 pb-2">
                  <h3 class="tracking-tight text-sm font-medium">Progress</h3>
                  <svg class="h-4 w-4 text-muted-foreground" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4M7.835 4.697a3.42 3.42 0 001.946-.806 3.42 3.42 0 014.438 0 3.42 3.42 0 001.946.806 3.42 3.42 0 013.138 3.138 3.42 3.42 0 00.806 1.946 3.42 3.42 0 010 4.438 3.42 3.42 0 00-.806 1.946 3.42 3.42 0 01-3.138 3.138 3.42 3.42 0 00-1.946.806 3.42 3.42 0 01-4.438 0 3.42 3.42 0 00-1.946-.806 3.42 3.42 0 01-3.138-3.138 3.42 3.42 0 00-.806-1.946 3.42 3.42 0 010-4.438 3.42 3.42 0 00.806-1.946 3.42 3.42 0 013.138-3.138z" />
                  </svg>
                </div>
                <div>
                  <div class="text-2xl font-bold">{{ getProgressPercentage() }}%</div>
                  <div class="w-full bg-muted rounded-full h-2 mt-2">
                    <div class="bg-primary h-2 rounded-full" [style.width.%]="getProgressPercentage()"></div>
                  </div>
                </div>
              </div>

              <!-- Evaluation -->
              <div class="rounded-lg border bg-card text-card-foreground shadow-sm p-6">
                <div class="flex flex-row items-center justify-between space-y-0 pb-2">
                  <h3 class="tracking-tight text-sm font-medium">Evaluation</h3>
                  <svg class="h-4 w-4 text-muted-foreground" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z" />
                  </svg>
                </div>
                <div>
                  <div class="text-2xl font-bold">4.2</div>
                  <p class="text-xs text-muted-foreground">
                    Average rating
                  </p>
                </div>
              </div>
            </div>

            <!-- Tasks and Applications Overview -->
            <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
              <!-- Recent Tasks -->
              <div class="rounded-lg border bg-card text-card-foreground shadow-sm p-6">
                <div class="mb-4">
                  <h3 class="font-semibold leading-none tracking-tight">Recent Tasks</h3>
                  <p class="text-sm text-muted-foreground">Your latest assignments and their status</p>
                </div>
                <div class="space-y-4">
                  @for (task of getMockTasks(); track task.id) {
                    <div class="flex items-center justify-between p-3 border rounded-lg">
                      <div class="flex-1">
                        <p class="font-medium text-sm">{{ task.title }}</p>
                        <div class="flex items-center gap-2 mt-1">
                          <span class="px-2 py-1 text-xs rounded-full"
                                [class.bg-green-100]="task.status === 'completed'"
                                [class.text-green-800]="task.status === 'completed'"
                                [class.bg-yellow-100]="task.status === 'in-progress'"
                                [class.text-yellow-800]="task.status === 'in-progress'"
                                [class.bg-gray-100]="task.status === 'pending'"
                                [class.text-gray-800]="task.status === 'pending'">
                            {{ task.status.replace('-', ' ') | titlecase }}
                          </span>
                          <span class="px-2 py-1 text-xs rounded-full"
                                [class.bg-red-100]="task.priority === 'high'"
                                [class.text-red-800]="task.priority === 'high'"
                                [class.bg-yellow-100]="task.priority === 'medium'"
                                [class.text-yellow-800]="task.priority === 'medium'"
                                [class.bg-green-100]="task.priority === 'low'"
                                [class.text-green-800]="task.priority === 'low'">
                            {{ task.priority | titlecase }}
                          </span>
                        </div>
                      </div>
                      <div class="text-xs text-muted-foreground">
                        Due: {{ formatDate(task.dueDate) }}
                      </div>
                    </div>
                  }
                </div>
              </div>

              <!-- Application Status -->
              <div class="rounded-lg border bg-card text-card-foreground shadow-sm p-6">
                <div class="mb-4">
                  <h3 class="font-semibold leading-none tracking-tight">Application Status</h3>
                  <p class="text-sm text-muted-foreground">Track your internship applications</p>
                </div>
                <div class="space-y-4">
                  @for (app of getMockApplications(); track app.id) {
                    <div class="flex items-center justify-between p-3 border rounded-lg">
                      <div class="flex-1">
                        <p class="font-medium text-sm">{{ app.position }}</p>
                        <p class="text-sm text-muted-foreground">{{ app.company }}</p>
                        <span class="px-2 py-1 text-xs rounded-full mt-1"
                              [class.bg-blue-100]="app.status === 'interview-scheduled'"
                              [class.text-blue-800]="app.status === 'interview-scheduled'"
                              [class.bg-yellow-100]="app.status === 'under-review'"
                              [class.text-yellow-800]="app.status === 'under-review'">
                          {{ app.status.replace('-', ' ') | titlecase }}
                        </span>
                      </div>
                      <div class="text-xs text-muted-foreground">
                        Applied: {{ formatDate(app.appliedDate) }}
                      </div>
                    </div>
                  }
                </div>
              </div>
            </div>
          </div>
        }
        @case ('profile') {
          <div class="space-y-6">
            <div class="rounded-lg border bg-card text-card-foreground shadow-sm p-6">
              <div class="mb-6">
                <h3 class="font-semibold leading-none tracking-tight">My Profile</h3>
                <p class="text-sm text-muted-foreground">Your personal and academic information</p>
              </div>
              
              <div class="space-y-6">
                <div class="flex items-center gap-4">
                  <div class="w-20 h-20 bg-muted rounded-full flex items-center justify-center">
                    <span class="text-lg font-semibold">{{ getUserInitials() }}</span>
                  </div>
                  <div>
                    <h3 class="text-xl font-semibold">{{ authService.user()?.name }}</h3>
                    <p class="text-muted-foreground">{{ authService.user()?.email }}</p>
                    <span class="px-2 py-1 text-xs rounded-full bg-secondary text-secondary-foreground mt-1 inline-block">
                      {{ authService.user()?.role | titlecase }}
                    </span>
                  </div>
                </div>

                <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div class="space-y-4">
                    <h4 class="font-medium">Contact Information</h4>
                    <div class="space-y-2">
                      <div>
                        <label class="text-sm text-muted-foreground">Email</label>
                        <p>{{ authService.user()?.email }}</p>
                      </div>
                      <div>
                        <label class="text-sm text-muted-foreground">Phone</label>
                        <p>{{ authService.user()?.phone || 'Not provided' }}</p>
                      </div>
                    </div>
                  </div>

                  <div class="space-y-4">
                    <h4 class="font-medium">Academic Information</h4>
                    <div class="space-y-2">
                      <div>
                        <label class="text-sm text-muted-foreground">University</label>
                        <p>{{ authService.user()?.university || 'Not provided' }}</p>
                      </div>
                      <div>
                        <label class="text-sm text-muted-foreground">Major</label>
                        <p>{{ authService.user()?.major || 'Not provided' }}</p>
                      </div>
                      @if (authService.user()?.graduationDate) {
                        <div>
                          <label class="text-sm text-muted-foreground">Expected Graduation</label>
                          <p>{{ authService.user()?.graduationDate }}</p>
                        </div>
                      }
                    </div>
                  </div>
                </div>

                @if (authService.user()?.skills && authService.user()?.skills!.length > 0) {
                  <div class="space-y-2">
                    <h4 class="font-medium">Skills & Interests</h4>
                    <div class="flex flex-wrap gap-2">
                      @for (skill of authService.user()?.skills; track skill) {
                        <span class="px-2 py-1 text-xs rounded-full border">{{ skill }}</span>
                      }
                    </div>
                  </div>
                }
              </div>
            </div>
          </div>
        }
        @default {
          <div class="text-center py-12 text-muted-foreground">
            {{ getCurrentSectionName() }} section coming soon...
          </div>
        }
      }
    </main>
  </div>
</div>
